server:
  port: 8085

spring:
  application:
    name: chat-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

info:
  app:
    name: chat-service
    description: Service de gestion des messages de chat
    version: 1.0.0