server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Support React Router (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy API calls au gateway
    location /incident-service/ {
        proxy_pass http://gateway:8080/incident-service/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /chat-service/ {
        proxy_pass http://gateway:8080/chat-service/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
}
